// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.27.1
// source: sip_proxy.proto

package proxy

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SIPTransport int32

const (
	SIPTransport_SIP_TRANSPORT_UNKNOWN SIPTransport = 0
	SIPTransport_SIP_TRANSPORT_UDP     SIPTransport = 1
	SIPTransport_SIP_TRANSPORT_TCP     SIPTransport = 2
	SIPTransport_SIP_TRANSPORT_TLS     SIPTransport = 3
)

// Enum value maps for SIPTransport.
var (
	SIPTransport_name = map[int32]string{
		0: "SIP_TRANSPORT_UNKNOWN",
		1: "SIP_TRANSPORT_UDP",
		2: "SIP_TRANSPORT_TCP",
		3: "SIP_TRANSPORT_TLS",
	}
	SIPTransport_value = map[string]int32{
		"SIP_TRANSPORT_UNKNOWN": 0,
		"SIP_TRANSPORT_UDP":     1,
		"SIP_TRANSPORT_TCP":     2,
		"SIP_TRANSPORT_TLS":     3,
	}
)

func (x SIPTransport) Enum() *SIPTransport {
	p := new(SIPTransport)
	*p = x
	return p
}

func (x SIPTransport) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SIPTransport) Descriptor() protoreflect.EnumDescriptor {
	return file_sip_proxy_proto_enumTypes[0].Descriptor()
}

func (SIPTransport) Type() protoreflect.EnumType {
	return &file_sip_proxy_proto_enumTypes[0]
}

func (x SIPTransport) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SIPTransport.Descriptor instead.
func (SIPTransport) EnumDescriptor() ([]byte, []int) {
	return file_sip_proxy_proto_rawDescGZIP(), []int{0}
}

type SIPInternalHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceIp      string                 `protobuf:"bytes,1,opt,name=source_ip,json=sourceIp,proto3" json:"source_ip,omitempty"`
	SourcePort    uint32                 `protobuf:"varint,2,opt,name=source_port,json=sourcePort,proto3" json:"source_port,omitempty"`
	Transport     SIPTransport           `protobuf:"varint,3,opt,name=transport,proto3,enum=proxy.SIPTransport" json:"transport,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SIPInternalHeader) Reset() {
	*x = SIPInternalHeader{}
	mi := &file_sip_proxy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SIPInternalHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SIPInternalHeader) ProtoMessage() {}

func (x *SIPInternalHeader) ProtoReflect() protoreflect.Message {
	mi := &file_sip_proxy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SIPInternalHeader.ProtoReflect.Descriptor instead.
func (*SIPInternalHeader) Descriptor() ([]byte, []int) {
	return file_sip_proxy_proto_rawDescGZIP(), []int{0}
}

func (x *SIPInternalHeader) GetSourceIp() string {
	if x != nil {
		return x.SourceIp
	}
	return ""
}

func (x *SIPInternalHeader) GetSourcePort() uint32 {
	if x != nil {
		return x.SourcePort
	}
	return 0
}

func (x *SIPInternalHeader) GetTransport() SIPTransport {
	if x != nil {
		return x.Transport
	}
	return SIPTransport_SIP_TRANSPORT_UNKNOWN
}

var File_sip_proxy_proto protoreflect.FileDescriptor

var file_sip_proxy_proto_rawDesc = string([]byte{
	0x0a, 0x0f, 0x73, 0x69, 0x70, 0x5f, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x22, 0x84, 0x01, 0x0a, 0x11, 0x53, 0x49, 0x50,
	0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x1b,
	0x0a, 0x09, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x69, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x70, 0x12, 0x1f, 0x0a, 0x0b, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x0a, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x31, 0x0a, 0x09,
	0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x13, 0x2e, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x53, 0x49, 0x50, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x70, 0x6f, 0x72, 0x74, 0x52, 0x09, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x2a,
	0x6e, 0x0a, 0x0c, 0x53, 0x49, 0x50, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x12,
	0x19, 0x0a, 0x15, 0x53, 0x49, 0x50, 0x5f, 0x54, 0x52, 0x41, 0x4e, 0x53, 0x50, 0x4f, 0x52, 0x54,
	0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x15, 0x0a, 0x11, 0x53, 0x49,
	0x50, 0x5f, 0x54, 0x52, 0x41, 0x4e, 0x53, 0x50, 0x4f, 0x52, 0x54, 0x5f, 0x55, 0x44, 0x50, 0x10,
	0x01, 0x12, 0x15, 0x0a, 0x11, 0x53, 0x49, 0x50, 0x5f, 0x54, 0x52, 0x41, 0x4e, 0x53, 0x50, 0x4f,
	0x52, 0x54, 0x5f, 0x54, 0x43, 0x50, 0x10, 0x02, 0x12, 0x15, 0x0a, 0x11, 0x53, 0x49, 0x50, 0x5f,
	0x54, 0x52, 0x41, 0x4e, 0x53, 0x50, 0x4f, 0x52, 0x54, 0x5f, 0x54, 0x4c, 0x53, 0x10, 0x03, 0x42,
	0x28, 0x5a, 0x26, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x69,
	0x76, 0x65, 0x6b, 0x69, 0x74, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2d, 0x73, 0x69, 0x70, 0x2f,
	0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
})

var (
	file_sip_proxy_proto_rawDescOnce sync.Once
	file_sip_proxy_proto_rawDescData []byte
)

func file_sip_proxy_proto_rawDescGZIP() []byte {
	file_sip_proxy_proto_rawDescOnce.Do(func() {
		file_sip_proxy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sip_proxy_proto_rawDesc), len(file_sip_proxy_proto_rawDesc)))
	})
	return file_sip_proxy_proto_rawDescData
}

var file_sip_proxy_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sip_proxy_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sip_proxy_proto_goTypes = []any{
	(SIPTransport)(0),         // 0: proxy.SIPTransport
	(*SIPInternalHeader)(nil), // 1: proxy.SIPInternalHeader
}
var file_sip_proxy_proto_depIdxs = []int32{
	0, // 0: proxy.SIPInternalHeader.transport:type_name -> proxy.SIPTransport
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_sip_proxy_proto_init() }
func file_sip_proxy_proto_init() {
	if File_sip_proxy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sip_proxy_proto_rawDesc), len(file_sip_proxy_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sip_proxy_proto_goTypes,
		DependencyIndexes: file_sip_proxy_proto_depIdxs,
		EnumInfos:         file_sip_proxy_proto_enumTypes,
		MessageInfos:      file_sip_proxy_proto_msgTypes,
	}.Build()
	File_sip_proxy_proto = out.File
	file_sip_proxy_proto_goTypes = nil
	file_sip_proxy_proto_depIdxs = nil
}
